import { mkdirSync, writeFileSync } from 'node:fs'
import path from 'node:path'

function titleCase(id: string): string {
  return id.split('-').map(part => part ? `${part[0]!.toUpperCase()}${part.slice(1)}` : '').join(' ')
}

export function createScaffoldPackageJson(appId: string) {
  return {
    name: `@aiworker-soul/${appId}`,
    private: true,
    scripts: {
      build: 'bun scripts/build.ts',
      smoke: 'aiworker app smoke .',
      test: 'bun test',
      typecheck: 'tsc --noEmit',
      validate: 'bun scripts/validate.ts',
    },
    type: 'module',
    version: '0.1.0',
    dependencies: {
      '@zonease/aiworker-soul-sdk': 'workspace:*',
    },
    devDependencies: {
      '@types/bun': '^1.2.13',
      'typescript': '^5.8.3',
    },
  }
}

export function createScaffoldTsconfig() {
  return {
    compilerOptions: {
      allowImportingTsExtensions: true,
      module: 'ESNext',
      moduleResolution: 'Bundler',
      noEmit: true,
      resolveJsonModule: true,
      strict: true,
      target: 'ES2022',
    },
    include: ['soul.config.ts', 'scripts/**/*.ts'],
  }
}

export function scaffoldSoulConfigTs(appId: string): string {
  const name = titleCase(appId)
  return `import { defineSoul } from '@zonease/aiworker-soul-sdk'

export default defineSoul({
  appId: '${appId}',
  description: 'Descriptor-only starter Soul for ${name}.',
  id: '${appId}',
  name: '${name}',
  soulId: '${appId}',
  version: '0.1.0',
})
`
}

export function scaffoldBuildScriptTs(): string {
  return `import process from 'node:process'
import { buildSoul } from '@zonease/aiworker-soul-sdk'

const result = await buildSoul(process.cwd())
process.stdout.write(\`\${JSON.stringify({
  descriptor: result.outputPath,
  generatedSections: result.discovery.generatedSections,
  status: result.status,
})}\\n\`)
`
}

export function scaffoldValidateScriptTs(): string {
  return `import process from 'node:process'
import { validateSoul } from '@zonease/aiworker-soul-sdk'

const result = await validateSoul(process.cwd())
process.stdout.write(\`\${JSON.stringify({
  discovery: result.discovery,
  issues: result.issues,
  status: result.status,
})}\\n\`)

if (result.status !== 'valid')
  process.exit(1)
`
}

export function scaffoldReadme(appId: string): string {
  const name = titleCase(appId)
  return [
    `# ${name} Soul`,
    '',
    'This scaffold is descriptor-only and uses the public Soul SDK authoring contract.',
    'The source of truth is `soul.config.ts`; `dist/soul.descriptor.json` is generated by `bun run build`.',
    '',
    '## Local Checks',
    '',
    '```bash',
    'bun run build',
    'aiworker app validate .',
    'aiworker app validate dist/soul.descriptor.json',
    'aiworker app smoke .',
    '```',
    '',
    'Keep app-owned engine files under `engine/`.',
    'Native MCP files may hold local author secrets, but descriptor output must not copy those values.',
    '',
  ].join('\n')
}

export function scaffoldWorkspaceAgents(appId: string): string {
  return [
    `# ${titleCase(appId)} Workspace Instructions`,
    '',
    'This workspace belongs to a descriptor-only AIWorker Soul.',
    'Use projected skills and native MCP config when available.',
    'Keep generated files reviewable before they become accepted workspace state.',
    '',
  ].join('\n')
}

export function scaffoldWorkspaceReadme(appId: string): string {
  return [
    '# {{workspaceName}}',
    '',
    `Workspace for ${titleCase(appId)}.`,
    '',
  ].join('\n')
}

export function scaffoldWorkspaceGitignore(): string {
  return [
    '.aiworker/sessions/',
    '.aiworker/projections.json',
    'evidence/raw/',
    '',
  ].join('\n')
}

export function scaffoldSkill(appId: string): string {
  return [
    '---',
    'name: default',
    `description: Run a descriptor-only ${titleCase(appId)} session.`,
    '---',
    '',
    '# Default Session',
    '',
    'Work inside the provided workspace root, use projected engine assets, and report progress through the native engine.',
    '',
  ].join('\n')
}

export function scaffoldCodexMcpConfig(): string {
  return '# Codex native MCP placeholder for this Soul.\n'
}

export function scaffoldClaudeCodeMcpConfig(): string {
  return '{ "mcpServers": {} }\n'
}

export function writeScaffoldFile(filePath: string, content: string): void {
  mkdirSync(path.dirname(filePath), { recursive: true })
  writeFileSync(filePath, content, { flag: 'wx' })
}
